### PR TITLE
User management #27

### LINKED ISSUE #27: user management page for webclient
Some new gRPC calls introduced with [recent changes](https://github.com/aau-network-security/haaukins/pull/403), which means, now we can delete, modifypasswd, and list users who are willing to use Haaukins for their events. I think, a proper user management page might look like WordPress management page like this, 

Screenshot 2020-05-21 at 20 08 10

This will remove the barrier of creating users by me or by @gianmarcomennecozzi, anyone who has admin privileges can modify user information. 

I hope, this will remove the barrier for any administrator who are using webclient. I am curious about your opinion @gianmarcomennecozzi. Let me know when you check the issue :) We can have a discussion or call.

### PR DESCRIPTION
**Pull request by gianmarcomennecozzi**
Screenshot from 2020-05-27 16-30-29

### CODE REVIEW

**Comment by mrtrkmn** [comment]
@gianmarcomennecozzi 

would it be possible to post UI screenshot of the page here  ?

**Comment by mrtrkmn** [comment]
@gianmarcomennecozzi 
I think, we should use, one common pattern for all repositories that we are working on for branch naming. 
Branches should start with either `hotfix/` or `feature/`.

**Review by mrtrkmn — CHANGES_REQUESTED** [review]
Nice ! 

Only thing is that branch naming, name of the branch should start with prefix of `hotfix/` or `feature/`. 

I think, I am going to take advantage of workflow that we have implemented in Richkit and imply that rule for all repositories that we are working with.

**Comment by gianmarcomennecozzi** [comment]
okay nice, i will start to use that branches name

**Pull request merged**
